# Development Server Port
server.port=8080

# Development Database
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Development Logging
logging.level.dev.project.urlshortener=DEBUG

# Development Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=30m

# JWT
jwt.secret=${JWT_SECRET:2Y9vGgNQ8wLz7ePqVhK5xRmC3JtUaF1nDs6B4iWpEzZkM0yHr8LfAcNvSjXuTb95}
jwt.expiration=${JWT_EXPIRATION:86400000}
